CREATE DATABASE IF NOT EXISTS `DB_NAME`;
CREATE DATABASE IF NOT EXISTS `test`;

CREATE USER 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'%';
GRANT ALL PRIVILEGES ON test.* TO 'DB_USER'@'%';
FLUSH PRIVILEGES;

USE DB_NAME;
