version: "3.7"

services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: services/app/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8082:8080
    volumes:
      - ./app:/usr/${APP_NAME}
    networks:
      - local

  db:
    container_name: ${APP_NAME}-db
    build:
      context: ./services/db
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-flush-method=O_DSYNC --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - local
    depends_on:
      - db

  #jenkins:
  #  container_name: ${APP_NAME}-jenkins
  #  image: jenkinsci/blueocean
  #  ports:
  #    - 8080:8080
  #    - 50000:50000
  #  volumes:
  #    - ./jenkins-data:/var/jenkins_home
  #    - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
